steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'stop', 'kty-tet-instance01-1', '--zone', 'asia-northeast3-b']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'stop', 'jgs-tet-instance01', '--zone', 'asia-northeast3-b']