steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'list']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', 'gs://kty-test1/git/']
  id: 'gcs-copy'


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'list', "--format", "csv(name,zone)", "|", "grep", "kty"]
  waitFor: ['gcs-copy'] 
