steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', 'gs://kty-test1/git/']
  id: 'gcs-copy'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud compute instances list --format="csv(name,zone.basename())" | grep kty- > /sc_vm_list/list.csv
      ssh-keygen -t rsa -f ~/root/.ssh/id_rsa
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  id: 'init-ssh'
  waitFor: ['gcs-copy']


- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat /sc_vm_list/list.csv
      gcloud compute ssh kty-instance-3 --zone=asia-northeast3-a --tunnel-through-iap --ssh-flag="-p 10022" --command="hostname"
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  waitFor: ['init-ssh']
