substitutions:
  _GIT_BUCKET: 'gs://kty-test1/git'

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', '$_GIT_BUCKET']
  id: 'gcs-copy'
  waitFor: ['set-env']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud compute instances list --format="csv(name,zone.basename(),status)" | grep RUNNING | grep kty- > /deploy/list.csv
      echo "Listing active kty prefix instances"
      echo "===================="
      cat /deploy/list.csv
      sh make-deploy.sh
      cat /deploy/deploy.yaml
  volumes:
  - name: 'deploy'
    path: '/deploy'
  id: 'build-deploy'
  waitFor: ['gcs-copy']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--no-source', '--async', '--config', '/deploy/deploy.yaml', '--substitutions', '_TRIGGER_BUILD=$BUILD_ID,_TRIGGER_REPO=$REPO_NAME,_TRIGGER_COMMIT=$COMMIT_SHA' ]
  volumes:
  - name: 'deploy'
    path: '/deploy'
  id: 'submit-deploy'
  waitFor: ['build-deploy']