steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'pping@kty-tet-instance01-1', '--zone', 'asia-northeast3-b', '--ssh-flag', '-p 10022', '--command', 'git clone https://github.com/silentbrain/stackdriversample.git /home/pping']
