steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', 'gs://kty-test1/git/']
  id: 'gcs-copy'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud compute instances list --format="csv(name,zone.basename(),status)" | grep RUNNING | grep kty- > /sc_vm_list/list.csv
      mkdir /builder/home/.ssh
      ssh-keygen -t rsa -f /builder/home/.ssh/google_compute_engine
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  id: 'init-ssh'
  waitFor: ['gcs-copy']


- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat /sc_vm_list/list.csv
      while IFS=',' read INSTANCE_NAME ZONE STATUS; 
      do 
        gcloud compute ssh pping@${INSTANCE_NAME} --zone=${ZONE} --tunnel-through-iap --ssh-flag="-p 10022" --command="hostname" &
      done < /sc_vm_list/list.csv
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  waitFor: ['init-ssh']
