steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', 'gs://kty-test1/git/']
  id: 'gcs-copy'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud compute instances list --format="csv(name,zone.basename(),status)" | grep RUNNING | grep kty- > /workspace/list.csv
      echo "Listing active kty prefix instances"
      cat /workspace/list.csv
  volumes:
  - name: 'workspace'
    path: '/workspace'
  id: 'list-vm'
  waitFor: ['gcs-copy']

- name: 'bash'
  args: ['./make-deploy.sh']
  volumes:
  - name: 'workspace'
    path: '/workspace'
  id: 'make-deploy.yaml'
  waitFor: ['list-vm']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - cat /workspace/deploy.yaml
  volumes:
  - name: 'workspace'
    path: '/workspace'
  id: 'cat-deploy.yaml'
  waitFor: ['make-deploy.yaml']

