
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'pping@kty-instance-2', '--zone', 'asia-northeast3-a', '--tunnel-through-iap', '--ssh-flag', '-p 10022', '--command', 'gsutil -m cp -r gs://kty-test1/git gs://kty-test1/after.sh /hosting/pping/ && sh /hosting/pping/after.sh']
  id: 'init-for-ssh'
  waitFor: ['gcs-copy']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'pping@kty-instance-3', '--zone', 'asia-northeast3-a', '--tunnel-through-iap', '--ssh-flag', '-p 10022', '--command', 'gsutil -m cp -r gs://kty-test1/git gs://kty-test1/after.sh /hosting/pping/ && sh /hosting/pping/after.sh']
  waitFor: ['init-for-ssh']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'pping@kty-instance-4', '--zone', 'asia-northeast3-a', '--tunnel-through-iap', '--ssh-flag', '-p 10022', '--command', 'gsutil -m cp -r gs://kty-test1/git gs://kty-test1/after.sh /hosting/pping/ && sh /hosting/pping/after.sh']
  waitFor: ['init-for-ssh']

options:
  workerPool:
    'projects/iaas-demo-208601/locations/asia-northeast3/workerPools/kty-dev-pool'
