steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './*', 'gs://kty-test1/git/']
  id: 'gcs-copy'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud auth list
      gcloud compute instances list --format="csv(name,zone.basename())" | grep kty- > /sc_vm_list/list.csv
      ssh-keygen
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  id: 'list_vm'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat /sc_vm_list/list.csv
  volumes:
  - name: 'sc_vm_list'
    path: '/sc_vm_list'
  waitFor: ['list_vm']
